// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVrgAQMAPGxTMLh0OiRR0o8KxHqZ6APnk',
    appId: '1:36759712128:web:2a362cc49a985e4ac49165',
    messagingSenderId: '36759712128',
    projectId: 'doodledash-a546b',
    authDomain: 'doodledash-a546b.firebaseapp.com',
    storageBucket: 'doodledash-a546b.appspot.com',
    measurementId: 'G-F4KYYY4S1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOolWyAOrwfxUyr_hHrtNXWlqoekuexxo',
    appId: '1:36759712128:android:62d3bfc0e02a2d19c49165',
    messagingSenderId: '36759712128',
    projectId: 'doodledash-a546b',
    storageBucket: 'doodledash-a546b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARj35SmUwrYp5xJkc6-IfCDyvSyvJf3mg',
    appId: '1:36759712128:ios:0bde0081d31575cfc49165',
    messagingSenderId: '36759712128',
    projectId: 'doodledash-a546b',
    storageBucket: 'doodledash-a546b.appspot.com',
    iosClientId: '36759712128-bkg0rtij7gug3pvq5uo30lbjnn1lai34.apps.googleusercontent.com',
    iosBundleId: 'com.example.doodleDash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARj35SmUwrYp5xJkc6-IfCDyvSyvJf3mg',
    appId: '1:36759712128:ios:a82eea7754f23f3fc49165',
    messagingSenderId: '36759712128',
    projectId: 'doodledash-a546b',
    storageBucket: 'doodledash-a546b.appspot.com',
    iosClientId: '36759712128-jdb5ahi3iqtja6eg1pooketv8721fso4.apps.googleusercontent.com',
    iosBundleId: 'com.example.doodleDash.RunnerTests',
  );
}
